server:
  port: 8080

neo4j:
  uri: bolt://172.19.80.53:7687
  username: neo4j
  password: 123456
  metrics-enabled: true
  pool:
    max-connection-pool-size: 100
    max-connection-lifetime: 30m
    connectionAcquisitionTimeout: 30s

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always